# Generated by Django 2.0.3 on 2018-03-31 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_reference', models.CharField(max_length=250)),
                ('mark_localization', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Picture_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('picture_date', models.DateField()),
                ('picture', models.ImageField(upload_to='')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pics.Mark')),
            ],
        ),
    ]
