# Generated by Django 2.0.3 on 2018-03-31 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='mark_localization',
            new_name='loc',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='mark_reference',
            new_name='ref',
        ),
    ]
