# Generated by Django 2.0.3 on 2018-04-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20180331_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_file',
            name='is_cancer',
            field=models.BooleanField(default=False),
        ),
    ]
