# Generated by Django 2.0.3 on 2018-04-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0004_auto_20180404_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture_file',
            name='picture',
        ),
    ]
