# Generated by Django 2.0.3 on 2018-04-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0007_mark_current_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_file',
            name='picture_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
