# Generated by Django 2.0.3 on 2018-04-27 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0009_mark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='is_cancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mark',
            name='picture_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
